version: '2.2'
services:
  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.9.2
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch:9200"]
    ports:
      - 5601:5601
  collector:
    image: cisco-mdt-collector
    command: -b "0.0.0.0:8080" -e "elasticsearch:9200" -i "mdt"
    ports:
      - 8080:8080

volumes:
  data01:
    driver: local
